server:
  port: 9090

spring:
  application:
    name: API_GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack

okta:
  oauth2:
    issuer: https://dev-83174035.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa804upylkK8gBVa5d7
    client-secret: 5ilRY8ljn8IRLuxVez_AhRmdk5LxvJZsB5mdvLS5
    scopes:
    - openid
    - profile
    - email
    - offline_access
