server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/paymentdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

okta:
  oauth2:
    issuer: https://dev-83174035.okta.com/oauth2/default
    audience: api://default    