server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-83174035.okta.com/oauth2/default
      client:
        provider:
          okta:
            issuer-uri: https://dev-83174035.okta.com/oauth2/default
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope:
            - internal
            client-id: 0oa804upylkK8gBVa5d7
            client-secret: 5ilRY8ljn8IRLuxVez_AhRmdk5LxvJZsB5mdvLS5

okta:
  oauth2:
    issuer: https://dev-83174035.okta.com/oauth2/default
    audience: api://default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
