server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296


# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
